version: '3.9'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"              # Adjust if needed (check with `id` command)
    network_mode: host             # Directly use host network (port 8096 by default)
    volumes:
      - ./config:/config           # Persistent configuration
      - ./cache:/cache             # Cache folder
      - ./media/music:/media/music # Example music library
      - ./media:/host-media        # Example media folder
      - ./fonts:/usr/local/share/fonts/custom:ro # Optional fonts
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
